# Generated by Django 2.1.7 on 2019-02-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190213_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('part_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pictures/kitchen')),
            ],
            options={
                'db_table': 'kitchen',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
